### ISSUE TITLE
AttributeError: 'CanvasBackend' object has no attribute 'setFocusPolicy' GUI.quit()

### ISSUE THREAD

**Issue by Kryschuuu** [shredEngineer/MagnetiCalc#1]
Hello,

I've installled it and want to start.

```
python3 -m pip install magneticalc --upgrade
python3 -m magneticalc
```

That's the Error log:

```
MagnetiCalc v1.8.6
Copyright © 2020, Paul Wilhelm, M. Sc. <mailto:anfrage@paulwilhelm.de>
ISC License (see README.md)


main/GUI: Init
main/__init__/Config.set_filename: file:///home/kris/MagnetiCalc/MagnetiCalc.ini
main/__init__/Config.load()
main/__init__/Model: Init
main/__init__/__init__/__init__/Wire_Widget.reinitialize()
main/__init__/__init__/__init__/reinitialize/set_wire/ModelAccess.enter()
main/__init__/__init__/__init__/reinitialize/set_wire/Wire: Init
main/__init__/__init__/__init__/reinitialize/set_wire/__init__/Wire.stretch()
main/__init__/__init__/__init__/reinitialize/set_wire/__init__/Wire._set_rotational_symmetry()
main/__init__/__init__/__init__/reinitialize/set_wire/ModelAccess.exit()
main/__init__/__init__/__init__/SamplingVolume_Widget.reinitialize()
main/__init__/__init__/__init__/reinitialize/Constraint_Editor.reinitialize()
main/__init__/__init__/__init__/reinitialize/set_sampling_volume/ModelAccess.enter()
main/__init__/__init__/__init__/reinitialize/set_sampling_volume/SamplingVolume: Init
main/__init__/__init__/__init__/reinitialize/set_sampling_volume/SamplingVolume_Widget.readjust()
main/__init__/__init__/__init__/reinitialize/set_sampling_volume/ModelAccess.exit()
main/__init__/__init__/__init__/Field_Widget.reinitialize()
main/__init__/__init__/__init__/reinitialize/set_field/ModelAccess.enter()
main/__init__/__init__/__init__/reinitialize/set_field/Field: Init
main/__init__/__init__/__init__/reinitialize/set_field/ModelAccess.exit()
main/__init__/__init__/__init__/Metric_Widget.reinitialize()
main/__init__/__init__/__init__/reinitialize/set_metric/ModelAccess.enter()
main/__init__/__init__/__init__/reinitialize/set_metric/Metric: Init
main/__init__/__init__/__init__/reinitialize/set_metric/ModelAccess.exit()
main/__init__/__init__/__init__/Parameters: Init
main/__init__/__init__/__init__/Display_Widget.reinitialize()
main/__init__/__init__/__init__/reinitialize/Display_Widget.update_label_resolution_combobox()
WARNING: Although PyQt5 is already imported, the PyQt5 backend could not
be used ("cannot import name 'QtOpenGL' from 'PyQt5' (/usr/lib/python3/dist-packages/PyQt5/__init__.py)"). 
Note that running multiple GUI toolkits simultaneously can cause side effects.

(python3:52051): Gtk-WARNING **: 18:42:24.449: gtk_disable_setlocale() must be called before gtk_init()
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kris/MagnetiCalc/magneticalc/__main__.py", line 49, in <module>
    main()
  File "/home/kris/MagnetiCalc/magneticalc/__main__.py", line 39, in main
    gui = GUI()
  File "/home/kris/MagnetiCalc/magneticalc/GUI.py", line 84, in __init__
    self.vispy_canvas.native.setFocusPolicy(Qt.NoFocus)  # Don't let VisPy gain control -- handle all events in GUI
AttributeError: 'CanvasBackend' object has no attribute 'setFocusPolicy'
GUI.quit()

Goodbye!
```

Any Ideas?

**Comment by Kryschuuu** [comment]
I've solved it.
Just simply: 

`python3 -m pip install numpy numba PyQt5 vispy qtawesome colorit si-prefix --upgrade
`

**Comment by shredEngineer** [comment]
Hi Kryschuuu,

I'm glad you were able to fix this so quickly. Let me know if you have any more questions or feedback! :)

Best wishes from Germany!
- Paul
